"""Main benchmark runner for PatentBench.

Orchestrates evaluation across models, domains, and tiers. Produces
structured results for leaderboard generation.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

from patentbench.config import (
    BENCHMARK_NAME,
    BENCHMARK_VERSION,
    DOMAIN_WEIGHTS,
    Domain,
    DifficultyTier,
    EvaluationLayer,
    LAYER_WEIGHTS,
)
from patentbench.data_loader import DataLoader, TestCase
from patentbench.evaluator import (
    DeterministicEvaluator,
    LLMJudgeEvaluator,
    ScoringAggregator,
)
from patentbench.metrics import EvaluationResult, MetricsCalculator


@dataclass
class BenchmarkConfig:
    """Configuration for a benchmark run."""

    subset: str = "mini"  # "mini", "full", "oa", "draft"
    domains: list[Domain] | None = None  # None = all domains
    tiers: list[DifficultyTier] | None = None  # None = all tiers
    max_cases: int | None = None
    output_dir: str = "results"
    run_deterministic: bool = True
    run_llm_judge: bool = True
    run_comparative: bool = False
    judge_model: str = "claude-sonnet-4-20250514"
    # Execution is intentionally sequential for reproducibility
    timeout_seconds: int = 120
    save_outputs: bool = True


@dataclass
class ModelOutput:
    """A model's response to a test case."""

    case_id: str
    model_name: str
    output: str
    latency_ms: float
    tokens_used: int = 0
    error: str | None = None


@dataclass
class BenchmarkResults:
    """Complete results from a benchmark run."""

    benchmark: str = BENCHMARK_NAME
    version: str = BENCHMARK_VERSION
    model_name: str = ""
    run_id: str = ""
    timestamp: str = ""
    config: dict[str, Any] = field(default_factory=dict)
    overall_score: float = 0.0
    domain_scores: dict[str, float] = field(default_factory=dict)
    tier_scores: dict[int, float] = field(default_factory=dict)
    layer_scores: dict[str, float] = field(default_factory=dict)
    case_results: list[dict[str, Any]] = field(default_factory=list)
    total_cases: int = 0
    pass_rate: float = 0.0
    total_latency_ms: float = 0.0
    total_tokens: int = 0
    statistics: dict[str, Any] = field(default_factory=dict)

    def summary(self) -> str:
        """Generate human-readable summary of results."""
        lines = [
            f"{'='*60}",
            f"  {self.benchmark} v{self.version} Results",
            f"  Model: {self.model_name}",
            f"  Run: {self.run_id}",
            f"  Timestamp: {self.timestamp}",
            f"{'='*60}",
            f"",
            f"  Overall Score: {self.overall_score:.1f}/100",
            f"  Pass Rate: {self.pass_rate:.1%}",
            f"  Total Cases: {self.total_cases}",
            f"",
            f"  Domain Scores:",
        ]
        for domain, score in sorted(self.domain_scores.items()):
            lines.append(f"    {domain:20s}: {score:.1f}")
        lines.append(f"")
        lines.append(f"  Tier Scores:")
        for tier, score in sorted(self.tier_scores.items()):
            tier_name = DifficultyTier(tier).display_name
            lines.append(f"    {tier_name:20s}: {score:.1f}")
        lines.append(f"")
        lines.append(f"  Layer Scores:")
        for layer, score in sorted(self.layer_scores.items()):
            lines.append(f"    {layer:20s}: {score:.1f}")
        lines.append(f"{'='*60}")
        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to the unified v0.2.0 results schema.

        This schema is the single source of truth — benchmark_results.json
        files MUST be generated by this method to ensure reproducibility.
        """
        # Compute human-readable summary stats
        tests_perfect = sum(
            1 for c in self.case_results
            if c.get("score", 0) == 1.0 or c.get("composite_score", 0) == 1.0
        )
        tests_with_errors = sum(
            1 for c in self.case_results if c.get("error")
        )

        # Group scores by task_type
        by_task_type: dict[str, dict[str, Any]] = {}
        for c in self.case_results:
            tt = c.get("task_type", "unknown")
            if tt not in by_task_type:
                by_task_type[tt] = {"total_score": 0.0, "cases": 0}
            by_task_type[tt]["cases"] += 1
            by_task_type[tt]["total_score"] += c.get("score", c.get("composite_score", 0.0))

        task_type_scores = {
            tt: {
                "score": round(v["total_score"] / v["cases"] * 100, 1) if v["cases"] else 0.0,
                "cases": v["cases"],
            }
            for tt, v in by_task_type.items()
        }

        return {
            "benchmark": self.benchmark,
            "version": self.version,
            "model": self.model_name,
            "run_id": self.run_id,
            "timestamp": self.timestamp,
            "config": self.config,
            "summary": {
                "overall_score": round(self.overall_score, 1),
                "total_cases": self.total_cases,
                "pass_rate": round(self.pass_rate, 4),
                "tests_perfect": tests_perfect,
                "tests_with_errors": tests_with_errors,
            },
            "scores": {
                "by_domain": {
                    d: {"score": round(s, 1), "cases": sum(
                        1 for c in self.case_results if c.get("domain") == d
                    )}
                    for d, s in self.domain_scores.items()
                },
                "by_tier": {
                    str(t): {"score": round(s, 1), "cases": sum(
                        1 for c in self.case_results if c.get("tier") == t
                    )}
                    for t, s in self.tier_scores.items()
                },
                "by_task_type": task_type_scores,
                "by_layer": {
                    l: {"score": round(s, 1), "weight": LAYER_WEIGHTS.get(
                        EvaluationLayer(l), 0.0
                    ) if l in [e.value for e in EvaluationLayer] else 0.0}
                    for l, s in self.layer_scores.items()
                },
            },
            "statistics": self.statistics,
            "case_results": self.case_results,
            "metadata": {
                "total_latency_ms": round(self.total_latency_ms, 1),
                "total_tokens": self.total_tokens,
                "harness_version": self.version,
            },
        }

    def save(self, path: str | Path) -> None:
        """Save results to JSON file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(self.to_dict(), f, indent=2)


class BenchmarkRunner:
    """Main benchmark execution engine.

    Orchestrates test case loading, model inference, and multi-layer evaluation.

    Usage:
        from patentbench.models.openai_adapter import OpenAIAdapter

        model = OpenAIAdapter(model_name="gpt-4o")
        runner = BenchmarkRunner(model=model)
        results = runner.run(BenchmarkConfig(subset="mini"))
    """

    def __init__(
        self,
        model: Any,  # BaseModelAdapter
        data_dir: str | Path = "data",
        config: BenchmarkConfig | None = None,
        cases: list[TestCase] | None = None,
        llm_judge_client: Any = None,  # LLMClient for Layer 2
    ) -> None:
        self.model = model
        self.data_dir = Path(data_dir)
        self.config = config or BenchmarkConfig()
        self._provided_cases = cases

        # Initialize evaluators
        self.deterministic_eval = DeterministicEvaluator()
        self.llm_judge_eval: LLMJudgeEvaluator | None = None
        if llm_judge_client and self.config.run_llm_judge:
            self.llm_judge_eval = LLMJudgeEvaluator(llm_client=llm_judge_client)
        self.aggregator = ScoringAggregator()

    def _load_cases(self) -> list[TestCase]:
        """Load test cases based on config."""
        if self._provided_cases is not None:
            return self._provided_cases

        subset_dir = self.data_dir / self.config.subset
        if not subset_dir.exists():
            subset_dir = self.data_dir

        loader = DataLoader(subset_dir)
        cases = loader.load_all()

        # Apply domain filter
        if self.config.domains:
            cases = [c for c in cases if c.domain in self.config.domains]

        # Apply tier filter
        if self.config.tiers:
            cases = [c for c in cases if c.tier in self.config.tiers]

        # Apply max cases limit
        if self.config.max_cases:
            cases = cases[: self.config.max_cases]

        return cases

    def _get_model_output(self, case: TestCase) -> ModelOutput:
        """Get model's response for a test case."""
        start_time = time.time()
        try:
            output = self.model.generate(case.prompt)
            latency_ms = (time.time() - start_time) * 1000
            return ModelOutput(
                case_id=case.id,
                model_name=getattr(self.model, "model_name", "unknown"),
                output=output,
                latency_ms=latency_ms,
            )
        except Exception as exc:
            latency_ms = (time.time() - start_time) * 1000
            return ModelOutput(
                case_id=case.id,
                model_name=getattr(self.model, "model_name", "unknown"),
                output="",
                latency_ms=latency_ms,
                error=str(exc),
            )

    def _evaluate_case(self, case: TestCase, model_output: ModelOutput) -> EvaluationResult:
        """Evaluate a single case through applicable evaluation layers."""
        if model_output.error:
            return EvaluationResult(
                case_id=case.id,
                model_name=model_output.model_name,
                model_output="",
                error=model_output.error,
            )

        result = EvaluationResult(
            case_id=case.id,
            model_name=model_output.model_name,
            model_output=model_output.output,
        )

        # Layer 1: Deterministic evaluation
        if self.config.run_deterministic and EvaluationLayer.DETERMINISTIC in case.evaluation_layers:
            det_result = self.deterministic_eval.evaluate(case, model_output.output)
            result.metrics.update(det_result.metrics)
            result.layer_scores.update(det_result.layer_scores)

        # Layer 2: LLM-Judge evaluation
        if (self.config.run_llm_judge
                and self.llm_judge_eval is not None
                and EvaluationLayer.LLM_JUDGE in case.evaluation_layers):
            try:
                judge_result = self.llm_judge_eval.evaluate(case, model_output.output)
                result.metrics.update(judge_result.metrics)
                result.layer_scores.update(judge_result.layer_scores)
            except Exception as exc:
                result.error = f"LLM-Judge error: {exc}"

        # Compute composite score
        all_scores = list(result.layer_scores.values())
        result.composite_score = sum(all_scores) / len(all_scores) if all_scores else 0.0
        result.passed = result.composite_score >= 0.5

        return result

    def run(self, config: BenchmarkConfig | None = None) -> BenchmarkResults:
        """Execute the benchmark.

        Args:
            config: Optional override config. Uses self.config if None.

        Returns:
            BenchmarkResults with complete evaluation data.
        """
        if config:
            self.config = config

        run_id = f"run_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}"
        cases = self._load_cases()

        if not cases:
            return BenchmarkResults(
                model_name=getattr(self.model, "model_name", "unknown"),
                run_id=run_id,
                timestamp=datetime.utcnow().isoformat(),
            )

        results: list[EvaluationResult] = []
        model_outputs: list[ModelOutput] = []
        total_latency = 0.0
        total_tokens = 0

        for case in cases:
            model_output = self._get_model_output(case)
            model_outputs.append(model_output)
            total_latency += model_output.latency_ms
            total_tokens += model_output.tokens_used

            eval_result = self._evaluate_case(case, model_output)
            results.append(eval_result)

        # Aggregate by domain
        domain_scores = self._aggregate_by_domain(results, cases)

        # Aggregate by tier
        tier_scores = self._aggregate_by_tier(results, cases)

        # Aggregate by layer
        aggregate = self.aggregator.aggregate(results)

        overall = sum(domain_scores.values()) / len(domain_scores) if domain_scores else 0.0

        # Build enriched case results with task metadata
        case_map = {c.id: c for c in cases}
        enriched_case_results = []
        for i, r in enumerate(results):
            case = case_map.get(r.case_id)
            details = []
            for metric_name, metric in r.metrics.items():
                if metric.value == 1.0:
                    details.append(f"{metric_name}: CORRECT")
                elif metric.value == 0.0:
                    details.append(f"{metric_name}: INCORRECT")
                else:
                    details.append(f"{metric_name}: {metric.value:.2f}")

            enriched_case_results.append({
                "case_id": r.case_id,
                "task_type": case.task_type if case else "unknown",
                "tier": case.tier.value if case else 0,
                "domain": case.domain.value if case else "unknown",
                "score": round(r.composite_score, 4),
                "passed": r.passed,
                "details": details,
                "latency_ms": round(model_outputs[i].latency_ms, 1) if i < len(model_outputs) else 0.0,
                "error": r.error,
            })

        # Compute bootstrap confidence intervals
        case_scores = [r.composite_score for r in results]
        overall_ci = MetricsCalculator.bootstrap_ci(case_scores)
        per_domain_ci: dict[str, Any] = {}
        case_map_for_ci = {c.id: c for c in cases}
        domain_score_lists: dict[str, list[float]] = {}
        for r in results:
            c = case_map_for_ci.get(r.case_id)
            if c:
                domain_score_lists.setdefault(c.domain.value, []).append(r.composite_score)
        for domain, dscores in domain_score_lists.items():
            ci_result = MetricsCalculator.bootstrap_ci(dscores)
            per_domain_ci[domain] = {
                "mean": round(ci_result.value * 100, 2),
                "ci_lower": round(ci_result.details["ci_lower"] * 100, 2),
                "ci_upper": round(ci_result.details["ci_upper"] * 100, 2),
                "n": ci_result.count,
            }
        statistics = {
            "overall_bootstrap_ci": {
                "mean": round(overall_ci.value * 100, 2),
                "ci_lower": round(overall_ci.details["ci_lower"] * 100, 2),
                "ci_upper": round(overall_ci.details["ci_upper"] * 100, 2),
                "ci_level": overall_ci.details["ci_level"],
                "n_bootstrap": overall_ci.details["n_bootstrap"],
                "n": overall_ci.count,
            },
            "per_domain_bootstrap_ci": per_domain_ci,
        }

        return BenchmarkResults(
            model_name=getattr(self.model, "model_name", "unknown"),
            run_id=run_id,
            timestamp=datetime.utcnow().isoformat(),
            config={
                "subset": self.config.subset,
                "domains": [d.value for d in self.config.domains] if self.config.domains else None,
                "tiers": [t.value for t in self.config.tiers] if self.config.tiers else None,
                "max_cases": self.config.max_cases,
                "run_deterministic": self.config.run_deterministic,
                "run_llm_judge": self.config.run_llm_judge,
            },
            overall_score=overall * 100,
            domain_scores={d: s * 100 for d, s in domain_scores.items()},
            tier_scores={t: s * 100 for t, s in tier_scores.items()},
            layer_scores={l: s * 100 for l, s in aggregate.get("layer_scores", {}).items()},
            case_results=enriched_case_results,
            total_cases=len(cases),
            pass_rate=aggregate.get("pass_rate", 0.0),
            total_latency_ms=total_latency,
            total_tokens=total_tokens,
            statistics=statistics,
        )

    def _aggregate_by_domain(
        self, results: list[EvaluationResult], cases: list[TestCase]
    ) -> dict[str, float]:
        """Compute average score per domain."""
        case_map = {c.id: c for c in cases}
        domain_scores: dict[str, list[float]] = {}
        for result in results:
            case = case_map.get(result.case_id)
            if case:
                domain = case.domain.value
                if domain not in domain_scores:
                    domain_scores[domain] = []
                domain_scores[domain].append(result.composite_score)

        return {
            domain: sum(scores) / len(scores) if scores else 0.0
            for domain, scores in domain_scores.items()
        }

    def _aggregate_by_tier(
        self, results: list[EvaluationResult], cases: list[TestCase]
    ) -> dict[int, float]:
        """Compute average score per difficulty tier."""
        case_map = {c.id: c for c in cases}
        tier_scores: dict[int, list[float]] = {}
        for result in results:
            case = case_map.get(result.case_id)
            if case:
                tier = case.tier.value
                if tier not in tier_scores:
                    tier_scores[tier] = []
                tier_scores[tier].append(result.composite_score)

        return {
            tier: sum(scores) / len(scores) if scores else 0.0
            for tier, scores in tier_scores.items()
        }
